package com.oscarcreator.sms_scheduler_v2.data.customer

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.oscarcreator.sms_scheduler_v2.data.AppDatabase
import com.oscarcreator.sms_scheduler_v2.data.scheduled.ScheduledTreatment

/**
 * [Customer] is a data class which is able to be inserted into the [AppDatabase]
 * */
@Entity(tableName = "customers")
data class Customer (
    /**
     * Id of the [Customer]. If this value is not specified it will be generated by SQLite
     * */
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name = "customer_id") val id: Long = 0,
    /**
     * Name of the [Customer].
     * */
    val name: String,
    /**
     * Phone number to the [Customer]. This phone number will be used to send notification for [ScheduledTreatment]s
     * */
    @ColumnInfo(name = "phone_number") val phoneNumber: String,
    /**
     * The money a [Customer] have left to use on treatments. This will be used
     * to track prebought treatments.
     * */
    val money: Int = 0
)