package com.oscarcreator.pigeon.data.message

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.oscarcreator.pigeon.data.AppDatabase
import com.oscarcreator.pigeon.data.contact.Contact
import java.util.*

/**
 * [Message] is a data class which is able to be inserted into the [AppDatabase]
 * */
@Entity(tableName = "messages")
data class Message(

    /**
     * The message which will be formatted and then sent to the [Contact]s
     * */
    val message: String,

    /**
     * A boolean to specify if this message have references and have been deleted by user
     * */
    @ColumnInfo(name = "to_be_deleted") val toBeDeleted: Boolean = false,

    /**
     * Id of the [Message]. If this value is not specified it will be generated by SQLite
     * */
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name = "message_id") val messageId: Long = 0,

    /**
     * The version of the edited message group
     * */
    @ColumnInfo(name = "message_version") val messageVersion: Long = 0,

    /**
     * The id of the group of messages edited.
     * */
    @ColumnInfo(name = "message_group_id") val messageGroupId: String = UUID.randomUUID().toString(),

    /**
     * Time message created.
     * */
    @ColumnInfo(name = "message_created") val messageCreated: Calendar = Calendar.getInstance(),

)