package com.oscarcreator.sms_scheduler_v2.data.message

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.oscarcreator.sms_scheduler_v2.data.AppDatabase
import com.oscarcreator.sms_scheduler_v2.data.contact.Contact

/**
 * [Message] is a data class which is able to be inserted into the [AppDatabase]
 * */
@Entity(tableName = "message")
data class Message(
    /**
     * Id of the [Message]. If this value is not specified it will be generated by SQLite
     * */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    /**
     * The message which will be formatted and then sent to the [Contact]s
     * */
    val message: String,
    /**
     * A boolean to specify if this message is able to be used by other scheduled messages
     * */
    val isTemplate: Boolean = false
)