package com.oscarcreator.sms_scheduler_v2.data.contact

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.oscarcreator.sms_scheduler_v2.data.AppDatabase
import com.oscarcreator.sms_scheduler_v2.data.scheduled.ScheduledTreatment

/**
 * [Contact] is a data class which is able to be inserted into the [AppDatabase]
 * */
@Entity(tableName = "contacts")
data class Contact (
    /**
     * Id of the [Contact]. If this value is not specified it will be generated by SQLite
     * */
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name = "contact_id") val id: Long = 0,
    /**
     * Name of the [Contact].
     * */
    val name: String,
    /**
     * Phone number to the [Contact]. This phone number will be used to send notification for [ScheduledTreatment]s
     * */
    @ColumnInfo(name = "phone_number") val phoneNumber: String,
    /**
     * The money a [Contact] have left to use on treatments. This will be used
     * to track prebought treatments.
     * */
    val money: Int = 0
)