package com.oscarcreator.pigeon.data.contact

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import com.oscarcreator.pigeon.data.AppDatabase
import com.oscarcreator.pigeon.data.scheduled.ScheduledTreatment
import java.util.*

/**
 * [Contact] is a data class which is able to be inserted into the [AppDatabase]
 * */
@Entity(tableName = "contacts")
data class Contact (

    /**
     * Name of the [Contact].
     * */
    val name: String,

    /**
     * Phone number to the [Contact]. This phone number will be used to send notification for [ScheduledTreatment]s
     * */
    @ColumnInfo(name = "phone_number") val phoneNumber: String,

    /**
     * The money a [Contact] have left to use on treatments. This will be used
     * to track prebought treatments.
     * */
    val money: Int = 0,

    /**
     * If the [Contact] should be deleted but has references mark this as true.
     * */
    @ColumnInfo(name = "to_be_deleted") val toBeDeleted: Boolean = false,

    /**
     * Id of the [Contact]. If this value is not specified it will be generated by SQLite
     * */
    @PrimaryKey(autoGenerate = true) @ColumnInfo(name = "contact_id") val contactId: Long = 0,

    /**
     * The version of the [Contact].
     * */
    @ColumnInfo(name = "contact_version") val contactVersion: Long = 0,

    /**
     * Id of the group of [Contact]s. All edited contacts with references will have same group id.
     * */
    @ColumnInfo(name = "contact_group_id") val contactGroupId: String = UUID.randomUUID().toString(),

    /**
     * Time which the contact is created.
     * */
    @ColumnInfo(name = "contact_created") val contactCreated: Calendar = Calendar.getInstance()

)