name: Run Tests on PR
on: [pull_request,workflow_dispatch]

jobs:
  connected-tests:
    runs-on: ${{ matrix.os }}
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
    timeout-minutes: 15
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        api-level: [33, 29]
        target: [default, google_apis]
        arch: [x86]
        exclude:
          - os: ubuntu-latest
            api-level: 33
          - os: ubuntu-latest
            api-level: 29
          - target: google_apis
            api-level: 33
          - target: google_apis
            api-level: 29
        include:
          - os: macos-latest
            api-level: 24
            target: playstore
            arch: x86
          - os: macos-latest
            api-level: 30
            target: aosp_atd
            arch: x86
          - os: macos-11
            api-level: 31
            target: google_apis
            arch: x86_64
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: 'gradle'
          
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
        
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-${{ matrix.os }}-${{ matrix.target }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          profile: Galaxy Nexus
          cores: 2
          sdcard-path-or-size: 100M
          avd-name: test
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          script: echo "Generated AVD snapshot for caching."

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          profile: Galaxy Nexus
          cores: 2
          sdcard-path-or-size: 100M
          avd-name: test
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          script: |
            adb devices
            chmod +x ./gradlew && ./gradlew connectedCheck

      - name: Upload test report
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/androidTests/connected/
      - name: Write job summary
        if: success() || failure()
        run: |
          echo "app/build/reports/androidTests/connected/index.html" >> $GITHUB_STEP_SUMMARY
